AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless stack for the AI Chat API

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Handler: lambda_function.lambda_handler

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod

Outputs:
  ApiUrl:
    Description: 'URL of the deployed API'
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
