files:
  "/opt/my_custom_software/install.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/bin/bash
      # Your installation script here
      yum install -y ollama
      ollama run llama3.2:1b

commands:
  - command: "bash /opt/my_custom_software/install.sh"